server:
  session:
    timeout: 10
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  resources:
      static-locations: classpath:/resources/,classpath:/resources/static/
  ###################### mysql ###########################
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://database:3306/nideshop?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=false
    username: dev
    password: dev
  ####################### redis ##########################
  redis:
    host: localhost
    port: 6379
    password:

mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:mappers/*.xml
